panels=panel1

[panel1]
plugins=fancymenu, desktopswitch, quicklaunch, showdesktop, taskbar, mount, volume, tray, statusnotifier, worldclock
position=Bottom
desktop=0

[fancymenu]
buttonsAtTop=false
categoriesAtRight=false
favorites\1\desktopFile=/usr/share/applications/featherpad.desktop
favorites\2\desktopFile=/usr/share/applications/lubuntu-update.desktop
favorites\3\desktopFile=/usr/share/applications/pcmanfm-qt.desktop
favorites\4\desktopFile=/usr/share/applications/qterminal.desktop
favorites\size=4
filterClear=true
menu_file=/etc/xdg/menus/lxqt-applications-compact.menu
showText=false
type=fancymenu

[desktopswitch]
type=desktopswitch

[quicklaunch]
type=quicklaunch
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\size=1
alignment=Left

[taskbar]
type=taskbar
buttonWidth=200

[tray]
type=tray

[mount]
type=mount

[worldclock]
type=worldclock

[volume]
device=0
type=volume

[showdesktop]
alignment=Right
type=showdesktop

[statusnotifier]
alignment=Right
type=statusnotifier
